In [1]:
!pip install -q kaggle

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import os
from pathlib import Path
import zipfile
import pandas as pd

In [3]:
PROJECT_DIR = Path(r"C:\Users\prince raj\Vector Rag for Audit Platform")

RAW_DIR = PROJECT_DIR / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

print("Dataset will be stored in:")
print(RAW_DIR)

Dataset will be stored in:
C:\Users\prince raj\Vector Rag for Audit Platform\data\raw

In [5]:
!kaggle auth login

Your browser has been opened to visit:
  https://www.kaggle.com/api/v1/oauth2/authorize?response_type=code&client_id=kagglesdk&redirect_uri=http%3A%2F%2Flocalhost%3A8379&scope=resources.admin%3A%2A&state=07072497-5741-4d37-bedc-821cb2ba1417&code_challenge=8zFVefI7VTYORGg8WSmfNZzB-l7T9ZI3UuqcjuR1_Ck%3D&code_challenge_method=S256&response_mode=query


Warning: Looks like you're using an outdated `kaggle` version (installed: 2.1.2), please consider upgrading to the latest version (2.2.2)

You are now logged in as [princerajpriyam]

127.0.0.1 - - [17/Sep/2026 17:59:53] "GET /?code=CfDJ8OasvsPNS7VMiSwiBm2YVpPrjLFxd47KLmQdLZppN-WoHs45LbX_UKmgHnzRPZ97AvV-NEclmuTHB-hXhORB_q0PqAEe5eB8BOnuUd2xCbnNS19N-ExP4W9SOkVnmr93JjsC76yAuvFFDGq7gYwr__8hXxDbOsDxoHpua3mnJQN7ddrd_LP9g8a58TCevbRH7kkn3SYnBFlUwgapByUXEytiqlGT3h8LCL5K2-OeSvz_xJdNM4HDjbCsLxaCtB0CZiiKd539DMgAaATl62lwjHZ0kg5YoX8B7AUD0hur1FoiX_01xUaxesir13iyCjM&state=07072497-5741-4d37-bedc-821cb2ba1417 HTTP/1.1" 200 -

In [6]:
!pip install -U kaggle

Requirement already satisfied: kaggle in c:\users\prince raj\anaconda3\lib\site-packages (2.1.2)
Collecting kaggle
  Downloading kaggle-2.2.4-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: bleach in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: jupytext in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (1.19.3)
Collecting kagglesdk<1.0,>=0.1.35 (from kaggle)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (6.33.6)
Requirement already satisfied: python-dateutil in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\prince raj\anaconda3\lib\site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in c:\users\prince raj\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\prince raj\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\prince raj\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.23.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\prince raj\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\prince raj\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.22.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\prince raj\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\prince raj\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (308)
Requirement already satisfied: six>=1.5 in c:\users\prince raj\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\prince raj\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\prince raj\anaconda3\lib\site-packages (from requests->kaggle) (2025.8.3)
Requirement already satisfied: colorama in c:\users\prince raj\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-2.2.4-py3-none-any.whl (126 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Installing collected packages: kagglesdk, kaggle

  Attempting uninstall: kagglesdk

    Found existing installation: kagglesdk 0.1.23

    Uninstalling kagglesdk-0.1.23:

      Successfully uninstalled kagglesdk-0.1.23

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
  Attempting uninstall: kaggle
   ---------------------------------------- 0/2 [kagglesdk]
    Found existing installation: kaggle 2.1.2
   ---------------------------------------- 0/2 [kagglesdk]
    Uninstalling kaggle-2.1.2:
   ---------------------------------------- 0/2 [kagglesdk]
      Successfully uninstalled kaggle-2.1.2
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kaggle]
   ---------------------------------------- 2/2 [kaggle]

Successfully installed kaggle-2.2.4 kagglesdk-0.1.37

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
!kaggle datasets list -s gdpr

ref                                                               title                                                      size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------------------  --------------------------------------------------  -----------  --------------------------  -------------  ---------  ---------------
jessemostipak/gdpr-violations                                     GDPR Violations                                          110521  2020-04-20 17:57:03.513000           1042         15  0.8235294
andreibuliga1/gdpr-fines-20182020-updated-23012021                GDPR Fines 2018-2020 Updated 23.01.2021                   71606  2021-01-25 20:07:32.977000            272          7  0.9705882
tanmoyx/covid19-patient-precondition-dataset                      COVID-19 patient pre-condition dataset                  7922557  2020-07-22 16:37:50.563000          13716        195  0.9705882
eljailarisuhonen/gdpr-fines-in-eu-20182019-120-rows-8-columns     GDPR fines in EU 2018-2019 (120 rows, 8 columns)           3961  2019-12-10 07:25:43.467000            409          9  0.7058824
dalmacyali1905/the-relationship-between-gdpr-and-personal-data    the relationship between GDPR and Personal Data          269460  2021-02-07 14:37:46.373000            226          5  0.8235294
saurabhshahane/statsbomb-football-data                            Stats-Bomb Football Data                             1723057670  2026-09-16 19:14:36.253000           4690        125  0.875
createphotos/rivacy-native-blurred-environments-poc               Privacy-Native Blurred Environments (POC)              43913536  2026-06-04 14:01:01.007000              6          4  1
valentindefour/gdpr-fines-referential                             GDPR Fines Repository                                     44996  2022-12-31 18:03:02.963000            144          1  0.9117647
mhmda81/legal-ai-hallucination-benchmark-v2                       Legal AI Hallucination Benchmark V2                        5811  2026-09-02 23:42:22.953000             49          4  1
hamza49/uk-legislations                                           UK Legislations & GDPR                                300847372  2025-08-13 01:01:59.357000            102          1  0.8125
rajkumarl/ruddit-jigsaw-dataset                                   ruddit jigsaw dataset                                   7775266  2026-09-01 12:52:24.153000           3608         89  0.8235294
josoriopt/gdpr-articles                                           GDPR Articles                                             83726  2025-02-12 15:43:49.183000            147          0  0.9375
guardeec/gdpr-privacy-sensitivity-survey-dataset                  GDPR Privacy Sensitivity Survey Dataset                21207565  2026-01-21 15:07:10.113000             28          1  0.9411765
fernandopipaalves/synthetic-heart-disease-10k-patients-gdpr-safe  Synthetic Heart Disease: 10k Patients (GDPR Safe)        108341  2026-08-31 12:11:32.187000              4          1  1
simuletic/cctv-incident-dataset-fall-and-lying-down-detection     CCTV Incident Dataset -Fall & Lying Down Detection    170295805  2025-12-14 18:20:13.183000           2231         45  1
vivekgupta96/gdpr-p                                               GDPR P                                                  3065271  2026-04-28 16:56:48.520000              3          1  0.23529412
tielemarvin/european-license-plate-dataset-elpd                   European License Plate Dataset (ELPD) 2329 Images   11579387212  2025-12-19 21:09:25.500000            229          8  0.6875
yashdev01/synthetic-healthcare-admissions                         Synthetic Healthcare Admissions Dataset                 1581549  2025-09-02 07:44:10.857000            380         14  1
iuliabunescu23/gdpr-articles-dataset                              GDPR-articles-dataset                                    482213  2024-03-15 10:22:16.197000            223          1  0.3529412
simuletic/airport-drone-threat-and-safety-dataset                 Airport Drone Threat & Safety Dataset                 143360672  2025-12-30 10:27:29.097000            446         13  1

In [8]:
from pathlib import Path

PROJECT_DIR = Path(r"C:\Users\prince raj\Vector Rag for Audit Platform")

RAW_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"
VECTOR_DIR = PROJECT_DIR / "data" / "vector_db"

RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
VECTOR_DIR.mkdir(parents=True, exist_ok=True)

print("Folders created successfully!")
print(RAW_DIR)
print(PROCESSED_DIR)
print(VECTOR_DIR)

Folders created successfully!
C:\Users\prince raj\Vector Rag for Audit Platform\data\raw
C:\Users\prince raj\Vector Rag for Audit Platform\data\processed
C:\Users\prince raj\Vector Rag for Audit Platform\data\vector_db

In [9]:
DATASET = "josoriopt/gdpr-articles"

!kaggle datasets download -d {DATASET} -p "{RAW_DIR}" --unzip

Dataset URL: https://www.kaggle.com/datasets/josoriopt/gdpr-articles
License(s): GPL-3.0
Downloading gdpr-articles.zip to C:\Users\prince raj\Vector Rag for Audit Platform\data\raw

  0%|          | 0.00/81.8k [00:00<?, ?B/s]
100%|##########| 81.8k/81.8k [00:00<00:00, 280kB/s]
100%|##########| 81.8k/81.8k [00:00<00:00, 279kB/s]

In [10]:
for file in RAW_DIR.rglob("*"):
    if file.is_file():
        print(file)

C:\Users\prince raj\Vector Rag for Audit Platform\data\raw\articles.jsonl

In [11]:
import json

jsonl_file = RAW_DIR / "articles.jsonl"

with open(jsonl_file, "r", encoding="utf-8") as f:
    first_record = json.loads(f.readline())

print(first_record)
print("\nColumns/fields:")
print(first_record.keys())

{'input-text': 'Article 1 Subject-matter and objectives', 'output-text': '(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This Regulation protects fundamental rights and freedoms of natural persons and in particular their right to the protection of personal data. (3) The free movement of personal data within the Union shall be neither restricted nor prohibited for reasons connected with the protection of natural persons with regard to the processing of personal data.'}

Columns/fields:
dict_keys(['input-text', 'output-text'])

In [12]:
count = 0

with open(jsonl_file, "r", encoding="utf-8") as f:
    for line in f:
        if line.strip():
            count += 1

print("Total records:", count)

Total records: 272

In [13]:
with open(jsonl_file, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if line.strip():
            print(f"\n--- Record {i + 1} ---")
            print(json.loads(line))
            
        if i >= 4:
            break

--- Record 1 ---
{'input-text': 'Article 1 Subject-matter and objectives', 'output-text': '(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This Regulation protects fundamental rights and freedoms of natural persons and in particular their right to the protection of personal data. (3) The free movement of personal data within the Union shall be neither restricted nor prohibited for reasons connected with the protection of natural persons with regard to the processing of personal data.'}

--- Record 2 ---
{'input-text': 'Article 2 Material scope', 'output-text': '(1) This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing system or are intended to form part of a filing system. (2) This Regulation does not apply to the processing of personal data:\n        \n- in the course of an activity which falls outside the scope of Union law;\n\n\n- by the Member States when carrying out activities which fall within the scope of Chapter 2 of Title V of the TEU;\n\n\n- by a natural person in the course of a purely personal or household activity;\n\n\n- by competent authorities for the purposes of the prevention, investigation, detection or prosecution of criminal offences or the execution of criminal penalties, including the safeguarding against and the prevention of threats to public security. - in the course of an activity which falls outside the scope of Union law; - by the Member States when carrying out activities which fall within the scope of Chapter 2 of Title V of the TEU; - by a natural person in the course of a purely personal or household activity; - by competent authorities for the purposes of the prevention, investigation, detection or prosecution of criminal offences or the execution of criminal penalties, including the safeguarding against and the prevention of threats to public security. (3) For the processing of personal data by the Union institutions, bodies, offices and agencies, Regulation (EC) No 45/2001 applies. Regulation (EC) No 45/2001 and other Union legal acts applicable to such processing of personal data shall be adapted to the principles and rules of this Regulation in accordance with \nArticle 98\n. (4) This Regulation shall be without prejudice to the application of Directive 2000/31/EC, in particular of the liability rules of intermediary service providers in Articles 12 to 15 of that Directive.'}

--- Record 3 ---
{'input-text': 'Article 3 Territorial scope', 'output-text': '(1) This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processing takes place in the Union or not. (2) This Regulation applies to the processing of personal data of data subjects who are in the Union by a controller or processor not established in the Union, where the processing activities are related to:\n        \n- the offering of goods or services, irrespective of whether a payment of the data subject is required, to such data subjects in the Union; or\n\n\n- the monitoring of their behaviour as far as their behaviour takes place within the Union. - the offering of goods or services, irrespective of whether a payment of the data subject is required, to such data subjects in the Union; or - the monitoring of their behaviour as far as their behaviour takes place within the Union. (3) This Regulation applies to the processing of personal data by a controller not established in the Union, but in a place where Member State law applies by virtue of public international law.'}

--- Record 4 ---
{'input-text': 'Article 4 Definitions', 'output-text': "For the purposes of this Regulation: (1) ‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person; (2) ‘processing’ means any operation or set of operations which is performed on personal data or on sets of personal data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction; (3) ‘restriction of processing’ means the marking of stored personal data with the aim of limiting their processing in the future; (4) ‘profiling’ means any form of automated processing of personal data consisting of the use of personal data to evaluate certain personal aspects relating to a natural person, in particular to analyse or predict aspects concerning that natural person's performance at work, economic situation, health, personal preferences, interests, reliability, behaviour, location or movements; (5) ‘pseudonymisation’ means the processing of personal data in such a manner that the personal data can no longer be attributed to a specific data subject without the use of additional information, provided that such additional information is kept separately and is subject to technical and organisational measures to ensure that the personal data are not attributed to an identified or identifiable natural person; (6) ‘filing system’ means any structured set of personal data which are accessible according to specific criteria, whether centralised, decentralised or dispersed on a functional or geographical basis; (7) ‘controller’ means the natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of personal data; where the purposes and means of such processing are determined by Union or Member State law, the controller or the specific criteria for its nomination may be provided for by Union or Member State law; (8) ‘processor’ means a natural or legal person, public authority, agency or other body which processes personal data on behalf of the controller; (9) ‘recipient’ means a natural or legal person, public authority, agency or another body, to which the personal data are disclosed, whether a third party or not. However, public authorities which may receive personal data in the framework of a particular inquiry in accordance with Union or Member State law shall not be regarded as recipients; the processing of those data by those public authorities shall be in compliance with the applicable data protection rules according to the purposes of the processing; (10) ‘third party’ means a natural or legal person, public authority, agency or body other than the data subject, controller, processor and persons who, under the direct authority of the controller or processor, are authorised to process personal data; (11) ‘consent’ of the data subject means any freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her; (12) ‘personal data breach’ means a breach of security leading to the accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to, personal data transmitted, stored or otherwise processed; (13) ‘genetic data’ means personal data relating to the inherited or acquired genetic characteristics of a natural person which give unique information about the physiology or the health of that natural person and which result, in particular, from an analysis of a biological sample from the natural person in question; (14) ‘biometric data’ means personal data resulting from specific technical processing relating to the physical, physiological or behavioural characteristics of a natural person, which allow or confirm the unique identification of that natural person, such as facial images or dactyloscopic data; (15) ‘data concerning health’ means personal data related to the physical or mental health of a natural person, including the provision of health care services, which reveal information about his or her health status; (16) ‘main establishment’ means:\n        \n(a) as regards a controller with establishments in more than one Member State, the place of its central administration in the Union, unless the decisions on the purposes and means of the processing of personal data are taken in another establishment of the controller in the Union and the latter establishment has the power to have such decisions implemented, in which case the establishment having taken such decisions is to be considered to be the main establishment;\n\n\n(b) as regards a processor with establishments in more than one Member State, the place of its central administration in the Union, or, if the processor has no central administration in the Union, the establishment of the processor in the Union where the main processing activities in the context of the activities of an establishment of the processor take place to the extent that the processor is subject to specific obligations under this Regulation; (a) as regards a controller with establishments in more than one Member State, the place of its central administration in the Union, unless the decisions on the purposes and means of the processing of personal data are taken in another establishment of the controller in the Union and the latter establishment has the power to have such decisions implemented, in which case the establishment having taken such decisions is to be considered to be the main establishment; (b) as regards a processor with establishments in more than one Member State, the place of its central administration in the Union, or, if the processor has no central administration in the Union, the establishment of the processor in the Union where the main processing activities in the context of the activities of an establishment of the processor take place to the extent that the processor is subject to specific obligations under this Regulation; (17) ‘representative’ means a natural or legal person established in the Union who, designated by the controller or processor in writing pursuant to \nArticle 27\n, represents the controller or processor with regard to their respective obligations under this Regulation; (18) ‘enterprise’ means a natural or legal person engaged in an economic activity, irrespective of its legal form, including partnerships or associations regularly engaged in an economic activity; (19) ‘group of undertakings’ means a controlling undertaking and its controlled undertakings; (20) ‘binding corporate rules’ means personal data protection policies which are adhered to by a controller or processor established on the territory of a Member State for transfers or a set of transfers of personal data to a controller or processor in one or more third countries within a group of undertakings, or group of enterprises engaged in a joint economic activity; (21) ‘supervisory authority’ means an independent public authority which is established by a Member State pursuant to \nArticle 51\n; (22) ‘supervisory authority concerned’ means a supervisory authority which is concerned by the processing of personal data because:\n        \n(a) the controller or processor is established on the territory of the Member State of that supervisory authority;\n\n\n(b) data subjects residing in the Member State of that supervisory authority are substantially affected or likely to be substantially affected by the processing; or\n\n\n(c) a complaint has been lodged with that supervisory authority; (a) the controller or processor is established on the territory of the Member State of that supervisory authority; (b) data subjects residing in the Member State of that supervisory authority are substantially affected or likely to be substantially affected by the processing; or (c) a complaint has been lodged with that supervisory authority; (23) ‘cross-border processing’ means either:\n        \n(a) processing of personal data which takes place in the context of the activities of establishments in more than one Member State of a controller or processor in the Union where the controller or processor is established in more than one Member State; or\n\n\n(b) processing of personal data which takes place in the context of the activities of a single establishment of a controller or processor in the Union but which substantially affects or is likely to substantially affect data subjects in more than one Member State. (a) processing of personal data which takes place in the context of the activities of establishments in more than one Member State of a controller or processor in the Union where the controller or processor is established in more than one Member State; or (b) processing of personal data which takes place in the context of the activities of a single establishment of a controller or processor in the Union but which substantially affects or is likely to substantially affect data subjects in more than one Member State. (24) ‘relevant and reasoned objection’ means an objection to a draft decision as to whether there is an infringement of this Regulation, or whether envisaged action in relation to the controller or processor complies with this Regulation, which clearly demonstrates the significance of the risks posed by the draft decision as regards the fundamental rights and freedoms of data subjects and, where applicable, the free flow of personal data within the Union; (25) ‘information society service’ means a service as defined in point (b) of Article 1(1) of Directive (EU) 2015/1535 of the European Parliament and of the Council \n(19)\n; (26) ‘international organisation’ means an organisation and its subordinate bodies governed by public international law, or any other body which is set up by, or on the basis of, an agreement between two or more countries."}

--- Record 5 ---
{'input-text': 'Article 5 Principles relating to processing of personal data', 'output-text': '(1) Personal data shall be:\n        \n- processed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’);\n\n\n- collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall, in accordance with \nArticle 89(1)\n, not be considered to be incompatible with the initial purposes (‘purpose limitation’);\n\n\n- adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed (‘data minimisation’);\n\n\n- accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’);\n\n\n- kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with \nArticle 89(1)\n subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’);\n\n\n- processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’). - processed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’); - collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall, in accordance with \nArticle 89(1)\n, not be considered to be incompatible with the initial purposes (‘purpose limitation’); - adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed (‘data minimisation’); - accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with \nArticle 89(1)\n subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’). (2) The controller shall be responsible for, and be able to demonstrate compliance with, paragraph 1 (‘accountability’).'}

In [14]:
import json
import pandas as pd

records = []

with open(jsonl_file, "r", encoding="utf-8") as f:
    for line in f:
        if line.strip():
            records.append(json.loads(line))

df = pd.DataFrame(records)

print("Total records:", len(df))
print("Columns:", df.columns.tolist())
df.head()

Total records: 272
Columns: ['input-text', 'output-text']

,input-text,output-text
0,Article 1 Subject-matter and objectives,(1) This Regulation lays down rules relating t...
1,Article 2 Material scope,(1) This Regulation applies to the processing ...
2,Article 3 Territorial scope,(1) This Regulation applies to the processing ...
3,Article 4 Definitions,For the purposes of this Regulation: (1) ‘pers...
4,Article 5 Principles relating to processing of...,(1) Personal data shall be:\n \n- proce...

In [15]:
pd.set_option("display.max_colwidth", 200)

display(df.head(10))

,input-text,output-text
0,Article 1 Subject-matter and objectives,(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This ...
1,Article 2 Material scope,(1) This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing ...
2,Article 3 Territorial scope,"(1) This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processin..."
3,Article 4 Definitions,For the purposes of this Regulation: (1) ‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who ...
4,Article 5 Principles relating to processing of personal data,"(1) Personal data shall be:\n \n- processed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’);\n\n\n- collected for spec..."
5,Article 6 Lawfulness of processing,(1) Processing shall be lawful only if and to the extent that at least one of the following applies:\n \n- the data subject has given consent to the processing of his or her personal data f...
6,Article 7 Conditions for consent,"(1) Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented to processing of his or her personal data. (2) If the data subject's conse..."
7,Article 8 Conditions applicable to child's consent in relation to information society services,"(1) Where point (a) of Article 6(1) applies, in relation to the offer of information society services directly to a child, the processing of the personal data of a child shall be lawful where the ..."
8,Article 9 Processing of special categories of personal data,"(1) Processing of personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric ..."
9,Article 10 Processing of personal data relating to criminal convictions and offences,Processing of personal data relating to criminal convictions and offences or related security measures based on Article 6(1) shall be carried out only under the control of official authority or wh...

In [16]:
for column in df.columns:
    print("\nCOLUMN:", column)
    print("Example:", df[column].iloc[0])

COLUMN: input-text
Example: Article 1 Subject-matter and objectives

COLUMN: output-text
Example: (1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This Regulation protects fundamental rights and freedoms of natural persons and in particular their right to the protection of personal data. (3) The free movement of personal data within the Union shall be neither restricted nor prohibited for reasons connected with the protection of natural persons with regard to the processing of personal data.

In [17]:
csv_backup = PROCESSED_DIR / "gdpr_raw.csv"

df.to_csv(csv_backup, index=False, encoding="utf-8")

print("Saved:", csv_backup)

Saved: C:\Users\prince raj\Vector Rag for Audit Platform\data\processed\gdpr_raw.csv

In [18]:
# Show the available columns first
print(df.columns.tolist())

['input-text', 'output-text']

In [20]:
# Create RAG-ready dataframe

rag_df = pd.DataFrame()

rag_df["framework"] = "GDPR"

rag_df["clause_id"] = range(1, len(df) + 1)

# Keep both parts of the original dataset
rag_df["input_text"] = (
    df["input-text"]
    .fillna("")
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

rag_df["text"] = (
    df["output-text"]
    .fillna("")
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Remove empty records
rag_df = rag_df[
    (rag_df["input_text"].str.len() > 0) &
    (rag_df["text"].str.len() > 0)
].reset_index(drop=True)

print("Total RAG records:", len(rag_df))

display(rag_df.head())

Total RAG records: 272

,framework,clause_id,input_text,text
0,NaN,1,Article 1 Subject-matter and objectives,(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This ...
1,NaN,2,Article 2 Material scope,(1) This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing ...
2,NaN,3,Article 3 Territorial scope,"(1) This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processin..."
3,NaN,4,Article 4 Definitions,For the purposes of this Regulation: (1) ‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who ...
4,NaN,5,Article 5 Principles relating to processing of personal data,"(1) Personal data shall be: - processed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’); - collected for specified, explicit ..."

In [21]:
for i in range(min(5, len(rag_df))):
    print("=" * 80)
    print("Framework:", rag_df.loc[i, "framework"])
    print("Clause ID:", rag_df.loc[i, "clause_id"])
    print("\nINPUT:")
    print(rag_df.loc[i, "input_text"])
    print("\nOUTPUT:")
    print(rag_df.loc[i, "text"])

================================================================================
Framework: nan
Clause ID: 1

INPUT:
Article 1 Subject-matter and objectives

OUTPUT:
(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This Regulation protects fundamental rights and freedoms of natural persons and in particular their right to the protection of personal data. (3) The free movement of personal data within the Union shall be neither restricted nor prohibited for reasons connected with the protection of natural persons with regard to the processing of personal data.
================================================================================
Framework: nan
Clause ID: 2

INPUT:
Article 2 Material scope

OUTPUT:
(1) This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing system or are intended to form part of a filing system. (2) This Regulation does not apply to the processing of personal data: - in the course of an activity which falls outside the scope of Union law; - by the Member States when carrying out activities which fall within the scope of Chapter 2 of Title V of the TEU; - by a natural person in the course of a purely personal or household activity; - by competent authorities for the purposes of the prevention, investigation, detection or prosecution of criminal offences or the execution of criminal penalties, including the safeguarding against and the prevention of threats to public security. - in the course of an activity which falls outside the scope of Union law; - by the Member States when carrying out activities which fall within the scope of Chapter 2 of Title V of the TEU; - by a natural person in the course of a purely personal or household activity; - by competent authorities for the purposes of the prevention, investigation, detection or prosecution of criminal offences or the execution of criminal penalties, including the safeguarding against and the prevention of threats to public security. (3) For the processing of personal data by the Union institutions, bodies, offices and agencies, Regulation (EC) No 45/2001 applies. Regulation (EC) No 45/2001 and other Union legal acts applicable to such processing of personal data shall be adapted to the principles and rules of this Regulation in accordance with Article 98 . (4) This Regulation shall be without prejudice to the application of Directive 2000/31/EC, in particular of the liability rules of intermediary service providers in Articles 12 to 15 of that Directive.
================================================================================
Framework: nan
Clause ID: 3

INPUT:
Article 3 Territorial scope

OUTPUT:
(1) This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processing takes place in the Union or not. (2) This Regulation applies to the processing of personal data of data subjects who are in the Union by a controller or processor not established in the Union, where the processing activities are related to: - the offering of goods or services, irrespective of whether a payment of the data subject is required, to such data subjects in the Union; or - the monitoring of their behaviour as far as their behaviour takes place within the Union. - the offering of goods or services, irrespective of whether a payment of the data subject is required, to such data subjects in the Union; or - the monitoring of their behaviour as far as their behaviour takes place within the Union. (3) This Regulation applies to the processing of personal data by a controller not established in the Union, but in a place where Member State law applies by virtue of public international law.
================================================================================
Framework: nan
Clause ID: 4

INPUT:
Article 4 Definitions

OUTPUT:
For the purposes of this Regulation: (1) ‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person; (2) ‘processing’ means any operation or set of operations which is performed on personal data or on sets of personal data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction; (3) ‘restriction of processing’ means the marking of stored personal data with the aim of limiting their processing in the future; (4) ‘profiling’ means any form of automated processing of personal data consisting of the use of personal data to evaluate certain personal aspects relating to a natural person, in particular to analyse or predict aspects concerning that natural person's performance at work, economic situation, health, personal preferences, interests, reliability, behaviour, location or movements; (5) ‘pseudonymisation’ means the processing of personal data in such a manner that the personal data can no longer be attributed to a specific data subject without the use of additional information, provided that such additional information is kept separately and is subject to technical and organisational measures to ensure that the personal data are not attributed to an identified or identifiable natural person; (6) ‘filing system’ means any structured set of personal data which are accessible according to specific criteria, whether centralised, decentralised or dispersed on a functional or geographical basis; (7) ‘controller’ means the natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of personal data; where the purposes and means of such processing are determined by Union or Member State law, the controller or the specific criteria for its nomination may be provided for by Union or Member State law; (8) ‘processor’ means a natural or legal person, public authority, agency or other body which processes personal data on behalf of the controller; (9) ‘recipient’ means a natural or legal person, public authority, agency or another body, to which the personal data are disclosed, whether a third party or not. However, public authorities which may receive personal data in the framework of a particular inquiry in accordance with Union or Member State law shall not be regarded as recipients; the processing of those data by those public authorities shall be in compliance with the applicable data protection rules according to the purposes of the processing; (10) ‘third party’ means a natural or legal person, public authority, agency or body other than the data subject, controller, processor and persons who, under the direct authority of the controller or processor, are authorised to process personal data; (11) ‘consent’ of the data subject means any freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her; (12) ‘personal data breach’ means a breach of security leading to the accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to, personal data transmitted, stored or otherwise processed; (13) ‘genetic data’ means personal data relating to the inherited or acquired genetic characteristics of a natural person which give unique information about the physiology or the health of that natural person and which result, in particular, from an analysis of a biological sample from the natural person in question; (14) ‘biometric data’ means personal data resulting from specific technical processing relating to the physical, physiological or behavioural characteristics of a natural person, which allow or confirm the unique identification of that natural person, such as facial images or dactyloscopic data; (15) ‘data concerning health’ means personal data related to the physical or mental health of a natural person, including the provision of health care services, which reveal information about his or her health status; (16) ‘main establishment’ means: (a) as regards a controller with establishments in more than one Member State, the place of its central administration in the Union, unless the decisions on the purposes and means of the processing of personal data are taken in another establishment of the controller in the Union and the latter establishment has the power to have such decisions implemented, in which case the establishment having taken such decisions is to be considered to be the main establishment; (b) as regards a processor with establishments in more than one Member State, the place of its central administration in the Union, or, if the processor has no central administration in the Union, the establishment of the processor in the Union where the main processing activities in the context of the activities of an establishment of the processor take place to the extent that the processor is subject to specific obligations under this Regulation; (a) as regards a controller with establishments in more than one Member State, the place of its central administration in the Union, unless the decisions on the purposes and means of the processing of personal data are taken in another establishment of the controller in the Union and the latter establishment has the power to have such decisions implemented, in which case the establishment having taken such decisions is to be considered to be the main establishment; (b) as regards a processor with establishments in more than one Member State, the place of its central administration in the Union, or, if the processor has no central administration in the Union, the establishment of the processor in the Union where the main processing activities in the context of the activities of an establishment of the processor take place to the extent that the processor is subject to specific obligations under this Regulation; (17) ‘representative’ means a natural or legal person established in the Union who, designated by the controller or processor in writing pursuant to Article 27 , represents the controller or processor with regard to their respective obligations under this Regulation; (18) ‘enterprise’ means a natural or legal person engaged in an economic activity, irrespective of its legal form, including partnerships or associations regularly engaged in an economic activity; (19) ‘group of undertakings’ means a controlling undertaking and its controlled undertakings; (20) ‘binding corporate rules’ means personal data protection policies which are adhered to by a controller or processor established on the territory of a Member State for transfers or a set of transfers of personal data to a controller or processor in one or more third countries within a group of undertakings, or group of enterprises engaged in a joint economic activity; (21) ‘supervisory authority’ means an independent public authority which is established by a Member State pursuant to Article 51 ; (22) ‘supervisory authority concerned’ means a supervisory authority which is concerned by the processing of personal data because: (a) the controller or processor is established on the territory of the Member State of that supervisory authority; (b) data subjects residing in the Member State of that supervisory authority are substantially affected or likely to be substantially affected by the processing; or (c) a complaint has been lodged with that supervisory authority; (a) the controller or processor is established on the territory of the Member State of that supervisory authority; (b) data subjects residing in the Member State of that supervisory authority are substantially affected or likely to be substantially affected by the processing; or (c) a complaint has been lodged with that supervisory authority; (23) ‘cross-border processing’ means either: (a) processing of personal data which takes place in the context of the activities of establishments in more than one Member State of a controller or processor in the Union where the controller or processor is established in more than one Member State; or (b) processing of personal data which takes place in the context of the activities of a single establishment of a controller or processor in the Union but which substantially affects or is likely to substantially affect data subjects in more than one Member State. (a) processing of personal data which takes place in the context of the activities of establishments in more than one Member State of a controller or processor in the Union where the controller or processor is established in more than one Member State; or (b) processing of personal data which takes place in the context of the activities of a single establishment of a controller or processor in the Union but which substantially affects or is likely to substantially affect data subjects in more than one Member State. (24) ‘relevant and reasoned objection’ means an objection to a draft decision as to whether there is an infringement of this Regulation, or whether envisaged action in relation to the controller or processor complies with this Regulation, which clearly demonstrates the significance of the risks posed by the draft decision as regards the fundamental rights and freedoms of data subjects and, where applicable, the free flow of personal data within the Union; (25) ‘information society service’ means a service as defined in point (b) of Article 1(1) of Directive (EU) 2015/1535 of the European Parliament and of the Council (19) ; (26) ‘international organisation’ means an organisation and its subordinate bodies governed by public international law, or any other body which is set up by, or on the basis of, an agreement between two or more countries.
================================================================================
Framework: nan
Clause ID: 5

INPUT:
Article 5 Principles relating to processing of personal data

OUTPUT:
(1) Personal data shall be: - processed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’); - collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall, in accordance with Article 89(1) , not be considered to be incompatible with the initial purposes (‘purpose limitation’); - adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed (‘data minimisation’); - accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’). - processed lawfully, fairly and in a transparent manner in relation to the data subject (‘lawfulness, fairness and transparency’); - collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall, in accordance with Article 89(1) , not be considered to be incompatible with the initial purposes (‘purpose limitation’); - adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed (‘data minimisation’); - accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’). (2) The controller shall be responsible for, and be able to demonstrate compliance with, paragraph 1 (‘accountability’).

In [22]:
gdpr_file = PROCESSED_DIR / "gdpr_regulations.csv"

rag_df.to_csv(
    gdpr_file,
    index=False,
    encoding="utf-8"
)

print("Saved successfully:")
print(gdpr_file)

Saved successfully:
C:\Users\prince raj\Vector Rag for Audit Platform\data\processed\gdpr_regulations.csv

In [23]:
import pandas as pd

# Load the cleaned dataset
rag_df = pd.read_csv(gdpr_file)

print("Loaded records:", len(rag_df))

Loaded records: 272

In [24]:
def create_chunks(text, chunk_size=150, overlap=30):
    words = str(text).split()
    chunks = []

    start = 0

    while start < len(words):
        end = start + chunk_size
        chunk = " ".join(words[start:end])

        if chunk.strip():
            chunks.append(chunk)

        if end >= len(words):
            break

        start = end - overlap

    return chunks

In [25]:
chunk_records = []

for _, row in rag_df.iterrows():

    chunks = create_chunks(row["text"])

    for chunk_number, chunk in enumerate(chunks, start=1):

        chunk_records.append({
            "framework": row["framework"],
            "clause_id": row["clause_id"],
            "chunk_id": chunk_number,
            "input_text": row["input_text"],
            "text": chunk
        })

chunks_df = pd.DataFrame(chunk_records)

print("Original records:", len(rag_df))
print("Total chunks:", len(chunks_df))

display(chunks_df.head())

Original records: 272
Total chunks: 603

,framework,clause_id,chunk_id,input_text,text
0,NaN,1,1,Article 1 Subject-matter and objectives,(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This ...
1,NaN,2,1,Article 2 Material scope,(1) This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing ...
2,NaN,2,2,Article 2 Material scope,"investigation, detection or prosecution of criminal offences or the execution of criminal penalties, including the safeguarding against and the prevention of threats to public security. - in the c..."
3,NaN,2,3,Article 2 Material scope,"by the Union institutions, bodies, offices and agencies, Regulation (EC) No 45/2001 applies. Regulation (EC) No 45/2001 and other Union legal acts applicable to such processing of personal data sh..."
4,NaN,3,1,Article 3 Territorial scope,"(1) This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processin..."

In [26]:
chunks_df["word_count"] = chunks_df["text"].apply(
    lambda x: len(str(x).split())
)

print(chunks_df["word_count"].describe())

count    603.000000
mean     119.490879
std       40.619388
min       23.000000
25%       84.000000
50%      150.000000
75%      150.000000
max      150.000000
Name: word_count, dtype: float64

In [27]:
chunks_file = PROCESSED_DIR / "gdpr_rag_chunks.csv"

chunks_df.to_csv(
    chunks_file,
    index=False,
    encoding="utf-8"
)

print("RAG chunks saved successfully:")
print(chunks_file)

RAG chunks saved successfully:
C:\Users\prince raj\Vector Rag for Audit Platform\data\processed\gdpr_rag_chunks.csv

In [28]:
!pip install -q sentence-transformers faiss-cpu

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import pandas as pd
import numpy as np
import faiss

from sentence_transformers import SentenceTransformer

In [30]:
chunks_df = pd.read_csv(chunks_file)

print("Total chunks:", len(chunks_df))
display(chunks_df.head())

Total chunks: 603

,framework,clause_id,chunk_id,input_text,text,word_count
0,NaN,1,1,Article 1 Subject-matter and objectives,(1) This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data. (2) This ...,86
1,NaN,2,1,Article 2 Material scope,(1) This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing ...,150
2,NaN,2,2,Article 2 Material scope,"investigation, detection or prosecution of criminal offences or the execution of criminal penalties, including the safeguarding against and the prevention of threats to public security. - in the c...",150
3,NaN,2,3,Article 2 Material scope,"by the Union institutions, bodies, offices and agencies, Regulation (EC) No 45/2001 applies. Regulation (EC) No 45/2001 and other Union legal acts applicable to such processing of personal data sh...",77
4,NaN,3,1,Article 3 Territorial scope,"(1) This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processin...",150

In [31]:
model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully.

In [32]:
texts = chunks_df["text"].fillna("").tolist()

embeddings = model.encode(
    texts,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Embedding shape: (603, 384)

In [33]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings.astype("float32"))

print("FAISS index created successfully.")
print("Vectors stored:", index.ntotal)
print("Vector dimension:", dimension)

FAISS index created successfully.
Vectors stored: 603
Vector dimension: 384

In [34]:
faiss_file = VECTOR_DIR / "gdpr.index"

faiss.write_index(
    index,
    str(faiss_file)
)

print("FAISS database saved:")
print(faiss_file)

FAISS database saved:
C:\Users\prince raj\Vector Rag for Audit Platform\data\vector_db\gdpr.index

In [35]:
metadata_file = VECTOR_DIR / "gdpr_metadata.csv"

metadata_df = chunks_df[
    [
        "framework",
        "clause_id",
        "chunk_id",
        "input_text",
        "text"
    ]
].copy()

metadata_df.to_csv(
    metadata_file,
    index=False,
    encoding="utf-8"
)

print("Metadata saved:")
print(metadata_file)

Metadata saved:
C:\Users\prince raj\Vector Rag for Audit Platform\data\vector_db\gdpr_metadata.csv

In [36]:
loaded_index = faiss.read_index(str(faiss_file))

loaded_metadata = pd.read_csv(metadata_file)

print("FAISS vectors:", loaded_index.ntotal)
print("Metadata records:", len(loaded_metadata))

FAISS vectors: 603
Metadata records: 603

In [37]:
import faiss
import pandas as pd
from sentence_transformers import SentenceTransformer

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Load FAISS index
loaded_index = faiss.read_index(str(faiss_file))

# Load metadata
loaded_metadata = pd.read_csv(metadata_file)

print("FAISS vectors:", loaded_index.ntotal)
print("Metadata rows:", len(loaded_metadata))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

FAISS vectors: 603
Metadata rows: 603

In [38]:
def retrieve(query, k=5):
    
    # Convert query into embedding
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    ).astype("float32")
    
    # Search FAISS
    distances, indices = loaded_index.search(
        query_embedding,
        k
    )
    
    results = []
    
    for rank, idx in enumerate(indices[0]):
        
        if idx == -1:
            continue
        
        row = loaded_metadata.iloc[idx]
        
        results.append({
            "rank": rank + 1,
            "distance": float(distances[0][rank]),
            "framework": row["framework"],
            "clause_id": row["clause_id"],
            "chunk_id": row["chunk_id"],
            "text": row["text"]
        })
    
    return pd.DataFrame(results)

In [39]:
query = "Can a company keep customer personal data indefinitely?"

results = retrieve(query, k=5)

display(results)

,rank,distance,framework,clause_id,chunk_id,text
0,1,0.758920,NaN,138,3,"of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controlle..."
1,2,0.857234,NaN,5,2,"personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of ..."
2,3,0.948614,NaN,167,3,"one data subject is concerned, the right to receive the personal data should be without prejudice to the rights and freedoms of other data subjects in accordance with this Regulation. Furthermore,..."
3,4,0.949111,NaN,161,1,"(62) However, it is not necessary to impose the obligation to provide information where the data subject already possesses the information, where the recording or disclosure of the personal data i..."
4,5,0.966487,NaN,138,2,"communication of personal data concerning them which are being processed. Natural persons should be made aware of risks, rules, safeguards and rights in relation to the processing of personal data..."

In [40]:
for _, row in results.iterrows():
    
    print("=" * 100)
    print("Rank:", row["rank"])
    print("Distance:", row["distance"])
    print("Framework:", row["framework"])
    print("Clause ID:", row["clause_id"])
    print("Chunk ID:", row["chunk_id"])
    print("\nRetrieved Text:")
    print(row["text"])
    print()

====================================================================================================
Rank: 1
Distance: 0.7589201331138611
Framework: nan
Clause ID: 138
Chunk ID: 3

Retrieved Text:
of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controller for erasure or for a periodic review. Every reasonable step should be taken to ensure that personal data which are inaccurate are rectified or deleted. Personal data should be processed in a manner that ensures appropriate security and confidentiality of the personal data, including for preventing unauthorised access to or use of personal data and the equipment used for the processing.

====================================================================================================
Rank: 2
Distance: 0.8572337031364441
Framework: nan
Clause ID: 5
Chunk ID: 2

Retrieved Text:
personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’).

====================================================================================================
Rank: 3
Distance: 0.948614239692688
Framework: nan
Clause ID: 167
Chunk ID: 3

Retrieved Text:
one data subject is concerned, the right to receive the personal data should be without prejudice to the rights and freedoms of other data subjects in accordance with this Regulation. Furthermore, that right should not prejudice the right of the data subject to obtain the erasure of personal data and the limitations of that right as set out in this Regulation and should, in particular, not imply the erasure of personal data concerning the data subject which have been provided by him or her for the performance of a contract to the extent that and for as long as the personal data are necessary for the performance of that contract. Where technically feasible, the data subject should have the right to have the personal data transmitted directly from one controller to another.

====================================================================================================
Rank: 4
Distance: 0.9491109251976013
Framework: nan
Clause ID: 161
Chunk ID: 1

Retrieved Text:
(62) However, it is not necessary to impose the obligation to provide information where the data subject already possesses the information, where the recording or disclosure of the personal data is expressly laid down by law or where the provision of information to the data subject proves to be impossible or would involve a disproportionate effort. The latter could in particular be the case where processing is carried out for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes. In that regard, the number of data subjects, the age of the data and any appropriate safeguards adopted should be taken into consideration.

====================================================================================================
Rank: 5
Distance: 0.9664872288703918
Framework: nan
Clause ID: 138
Chunk ID: 2

Retrieved Text:
communication of personal data concerning them which are being processed. Natural persons should be made aware of risks, rules, safeguards and rights in relation to the processing of personal data and how to exercise their rights in relation to such processing. In particular, the specific purposes for which personal data are processed should be explicit and legitimate and determined at the time of the collection of the personal data. The personal data should be adequate, relevant and limited to what is necessary for the purposes for which they are processed. This requires, in particular, ensuring that the period for which the personal data are stored is limited to a strict minimum. Personal data should be processed only if the purpose of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established

In [41]:
def build_context(query, k=5):
    
    results = retrieve(query, k)
    
    context_parts = []
    
    for _, row in results.iterrows():
        
        context_parts.append(
            f"""Framework: {row['framework']}
Clause ID: {row['clause_id']}
Chunk ID: {row['chunk_id']}
Text: {row['text']}"""
        )
    
    return "\n\n".join(context_parts)

In [42]:
query = "How should an organization handle personal data retention?"

context = build_context(query, k=5)

print(context)

Framework: nan
Clause ID: 5
Chunk ID: 2
Text: personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’).

Framework: nan
Clause ID: 138
Chunk ID: 3
Text: of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controller for erasure or for a periodic review. Every reasonable step should be taken to ensure that personal data which are inaccurate are rectified or deleted. Personal data should be processed in a manner that ensures appropriate security and confidentiality of the personal data, including for preventing unauthorised access to or use of personal data and the equipment used for the processing.

Framework: nan
Clause ID: 5
Chunk ID: 4
Text: for which they are processed (‘data minimisation’); - accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the

Framework: nan
Clause ID: 161
Chunk ID: 1
Text: (62) However, it is not necessary to impose the obligation to provide information where the data subject already possesses the information, where the recording or disclosure of the personal data is expressly laid down by law or where the provision of information to the data subject proves to be impossible or would involve a disproportionate effort. The latter could in particular be the case where processing is carried out for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes. In that regard, the number of data subjects, the age of the data and any appropriate safeguards adopted should be taken into consideration.

Framework: nan
Clause ID: 257
Chunk ID: 1
Text: (158) Where personal data are processed for archiving purposes, this Regulation should also apply to that processing, bearing in mind that this Regulation should not apply to deceased persons. Public authorities or public or private bodies that hold records of public interest should be services which, pursuant to Union or Member State law, have a legal obligation to acquire, preserve, appraise, arrange, describe, communicate, promote, disseminate and provide access to records of enduring value for general public interest. Member States should also be authorised to provide for the further processing of personal data for archiving purposes, for example with a view to providing specific information related to the political behaviour under former totalitarian state regimes, genocide, crimes against humanity, in particular the Holocaust, or war crimes.

In [43]:
!pip install -q openai

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
from openai import OpenAI
import os

In [46]:
import os

print("API key available:", bool(os.getenv("OPENAI_API_KEY")))

API key available: False

In [47]:
import os
from getpass import getpass

os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API key: ")

print("API key loaded:", bool(os.getenv("OPENAI_API_KEY")))

Enter your OpenAI API key:  ········

API key loaded: True

In [48]:
from openai import OpenAI

client = OpenAI(
    api_key=os.environ["OPENAI_API_KEY"]
)

print("OpenAI client created successfully.")

OpenAI client created successfully.

In [50]:
policy = """
Our company retains all customer personal data indefinitely
and does not automatically delete old customer records.
"""

results = retrieve(policy, k=5)

display(
    results[
        [
            "rank",
            "distance",
            "framework",
            "clause_id",
            "chunk_id",
            "text"
        ]
    ]
)

,rank,distance,framework,clause_id,chunk_id,text
0,1,0.900313,NaN,138,3,"of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controlle..."
1,2,1.001194,NaN,165,1,"(66) To strengthen the right to be forgotten in the online environment, the right to erasure should also be extended in such a way that a controller who has made the personal data public should be..."
2,3,1.057424,NaN,17,1,(1) The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase...
3,4,1.069693,NaN,126,1,(27) This Regulation does not apply to the personal data of deceased persons. Member States may provide for rules regarding the processing of personal data of deceased persons.
4,5,1.088182,NaN,5,2,"personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of ..."

In [57]:
context = build_context(policy, k=5)

print("=" * 100)
print("RETRIEVED GDPR EVIDENCE")
print("=" * 100)
print(context)

====================================================================================================
RETRIEVED GDPR EVIDENCE
====================================================================================================
Framework: nan
Clause ID: 138
Chunk ID: 3
Text: of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controller for erasure or for a periodic review. Every reasonable step should be taken to ensure that personal data which are inaccurate are rectified or deleted. Personal data should be processed in a manner that ensures appropriate security and confidentiality of the personal data, including for preventing unauthorised access to or use of personal data and the equipment used for the processing.

Framework: nan
Clause ID: 165
Chunk ID: 1
Text: (66) To strengthen the right to be forgotten in the online environment, the right to erasure should also be extended in such a way that a controller who has made the personal data public should be obliged to inform the controllers which are processing such personal data to erase any links to, or copies or replications of those personal data. In doing so, that controller should take reasonable steps, taking into account available technology and the means available to the controller, including technical measures, to inform the controllers which are processing the personal data of the data subject's request.

Framework: nan
Clause ID: 17
Chunk ID: 1
Text: (1) The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase personal data without undue delay where one of the following grounds applies: - the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; - the data subject withdraws consent on which the processing is based according to point (a) of Article 6(1), or point (a) of Article 9(2), and where there is no other legal ground for the processing; - the data subject objects to the processing pursuant to Article 21(1) and there are no overriding legitimate grounds for the processing, or the data subject objects to the processing pursuant to Article 21(2); - the personal data have been unlawfully processed; - the personal data have

Framework: nan
Clause ID: 126
Chunk ID: 1
Text: (27) This Regulation does not apply to the personal data of deceased persons. Member States may provide for rules regarding the processing of personal data of deceased persons.

Framework: nan
Clause ID: 5
Chunk ID: 2
Text: personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’).

In [58]:
compliance_rules = {
    "data_retention": [
        "retain personal data indefinitely",
        "delete old customer records",
        "retention period",
        "storage limitation",
        "delete personal data",
        "erase personal data"
    ],
    
    "data_collection": [
        "collect personal data",
        "necessary personal data",
        "purpose of collection",
        "data minimization"
    ],
    
    "data_security": [
        "protect personal data",
        "security measures",
        "unauthorized access",
        "encryption"
    ]
}

print("Compliance rules loaded:", len(compliance_rules))

Compliance rules loaded: 3

In [59]:
def detect_compliance_area(policy):
    policy_lower = policy.lower()
    
    matched_areas = []
    
    for area, keywords in compliance_rules.items():
        for keyword in keywords:
            if keyword in policy_lower:
                matched_areas.append(area)
                break
    
    return matched_areas


areas = detect_compliance_area(policy)

print("Detected compliance areas:")
for area in areas:
    print("-", area)

Detected compliance areas:
- data_retention

In [60]:
def rule_based_audit(policy, k=5):
    results = retrieve(policy, k=k)
    
    areas = detect_compliance_area(policy)
    
    if len(results) == 0:
        verdict = "INSUFFICIENT EVIDENCE"
        risk = "UNKNOWN"
    else:
        if "data_retention" in areas:
            verdict = "REVIEW REQUIRED"
            risk = "HIGH"
        else:
            verdict = "REVIEW REQUIRED"
            risk = "MEDIUM"
    
    evidence = []
    
    for _, row in results.iterrows():
        evidence.append({
            "framework": row["framework"],
            "record_id": int(row["clause_id"]),
            "chunk_id": int(row["chunk_id"]),
            "distance": round(float(row["distance"]), 4),
            "text": row["text"]
        })
    
    return {
        "policy": policy.strip(),
        "compliance_areas": areas,
        "verdict": verdict,
        "risk": risk,
        "evidence": evidence
    }

In [61]:
audit_report = rule_based_audit(policy, k=5)

print("Verdict:", audit_report["verdict"])
print("Risk:", audit_report["risk"])
print("Areas:", audit_report["compliance_areas"])

Verdict: REVIEW REQUIRED
Risk: HIGH
Areas: ['data_retention']

In [62]:
for item in audit_report["evidence"]:
    print("\nFramework:", item["framework"])
    print("Record ID:", item["record_id"])
    print("Chunk ID:", item["chunk_id"])
    print("Distance:", item["distance"])
    print("Evidence:", item["text"])

Framework: nan
Record ID: 138
Chunk ID: 3
Distance: 0.9003
Evidence: of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controller for erasure or for a periodic review. Every reasonable step should be taken to ensure that personal data which are inaccurate are rectified or deleted. Personal data should be processed in a manner that ensures appropriate security and confidentiality of the personal data, including for preventing unauthorised access to or use of personal data and the equipment used for the processing.

Framework: nan
Record ID: 165
Chunk ID: 1
Distance: 1.0012
Evidence: (66) To strengthen the right to be forgotten in the online environment, the right to erasure should also be extended in such a way that a controller who has made the personal data public should be obliged to inform the controllers which are processing such personal data to erase any links to, or copies or replications of those personal data. In doing so, that controller should take reasonable steps, taking into account available technology and the means available to the controller, including technical measures, to inform the controllers which are processing the personal data of the data subject's request.

Framework: nan
Record ID: 17
Chunk ID: 1
Distance: 1.0574
Evidence: (1) The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase personal data without undue delay where one of the following grounds applies: - the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; - the data subject withdraws consent on which the processing is based according to point (a) of Article 6(1), or point (a) of Article 9(2), and where there is no other legal ground for the processing; - the data subject objects to the processing pursuant to Article 21(1) and there are no overriding legitimate grounds for the processing, or the data subject objects to the processing pursuant to Article 21(2); - the personal data have been unlawfully processed; - the personal data have

Framework: nan
Record ID: 126
Chunk ID: 1
Distance: 1.0697
Evidence: (27) This Regulation does not apply to the personal data of deceased persons. Member States may provide for rules regarding the processing of personal data of deceased persons.

Framework: nan
Record ID: 5
Chunk ID: 2
Distance: 1.0882
Evidence: personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’).

In [64]:
def calculate_compliance_score(audit_report):
    score = 100
    
    if audit_report["risk"] == "HIGH":
        score -= 40
    elif audit_report["risk"] == "MEDIUM":
        score -= 20
    
    if audit_report["verdict"] == "INSUFFICIENT EVIDENCE":
        score = 0
    
    return max(0, score)


score = calculate_compliance_score(audit_report)

print("Compliance Score:", score, "/ 100")

Compliance Score: 60 / 100

In [65]:
def generate_recommendations(audit_report):
    recommendations = []
    
    if "data_retention" in audit_report["compliance_areas"]:
        recommendations.append(
            "Define a clear retention period for customer personal data."
        )
        recommendations.append(
            "Automatically delete or anonymize personal data when it is no longer required."
        )
    
    if "data_collection" in audit_report["compliance_areas"]:
        recommendations.append(
            "Collect only personal data that is necessary for the stated purpose."
        )
    
    if "data_security" in audit_report["compliance_areas"]:
        recommendations.append(
            "Implement appropriate security measures to protect personal data."
        )
    
    if not recommendations:
        recommendations.append(
            "Review the policy against the available regulatory evidence."
        )
    
    return recommendations


recommendations = generate_recommendations(audit_report)

print("Recommendations:")
for i, recommendation in enumerate(recommendations, 1):
    print(f"{i}. {recommendation}")

Recommendations:
1. Define a clear retention period for customer personal data.
2. Automatically delete or anonymize personal data when it is no longer required.

In [66]:
audit_report["compliance_score"] = score
audit_report["recommendations"] = recommendations

audit_report

{'policy': 'Our company retains all customer personal data indefinitely\nand does not automatically delete old customer records.',
 'compliance_areas': ['data_retention'],
 'verdict': 'REVIEW REQUIRED',
 'risk': 'HIGH',
 'evidence': [{'framework': nan,
   'record_id': 138,
   'chunk_id': 3,
   'distance': 0.9003,
   'text': 'of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controller for erasure or for a periodic review. Every reasonable step should be taken to ensure that personal data which are inaccurate are rectified or deleted. Personal data should be processed in a manner that ensures appropriate security and confidentiality of the personal data, including for preventing unauthorised access to or use of personal data and the equipment used for the processing.'},
  {'framework': nan,
   'record_id': 165,
   'chunk_id': 1,
   'distance': 1.0012,
   'text': "(66) To strengthen the right to be forgotten in the online environment, the right to erasure should also be extended in such a way that a controller who has made the personal data public should be obliged to inform the controllers which are processing such personal data to erase any links to, or copies or replications of those personal data. In doing so, that controller should take reasonable steps, taking into account available technology and the means available to the controller, including technical measures, to inform the controllers which are processing the personal data of the data subject's request."},
  {'framework': nan,
   'record_id': 17,
   'chunk_id': 1,
   'distance': 1.0574,
   'text': '(1) The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase personal data without undue delay where one of the following grounds applies: - the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; - the data subject withdraws consent on which the processing is based according to point (a) of Article 6(1), or point (a) of Article 9(2), and where there is no other legal ground for the processing; - the data subject objects to the processing pursuant to Article 21(1) and there are no overriding legitimate grounds for the processing, or the data subject objects to the processing pursuant to Article 21(2); - the personal data have been unlawfully processed; - the personal data have'},
  {'framework': nan,
   'record_id': 126,
   'chunk_id': 1,
   'distance': 1.0697,
   'text': '(27) This Regulation does not apply to the personal data of deceased persons. Member States may provide for rules regarding the processing of personal data of deceased persons.'},
  {'framework': nan,
   'record_id': 5,
   'chunk_id': 2,
   'distance': 1.0882,
   'text': 'personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’).'}],
 'compliance_score': 60,
 'recommendations': ['Define a clear retention period for customer personal data.',
  'Automatically delete or anonymize personal data when it is no longer required.']}

In [67]:
import json

audit_json = json.dumps(
    audit_report,
    indent=4,
    ensure_ascii=False
)

print(audit_json)

{
    "policy": "Our company retains all customer personal data indefinitely\nand does not automatically delete old customer records.",
    "compliance_areas": [
        "data_retention"
    ],
    "verdict": "REVIEW REQUIRED",
    "risk": "HIGH",
    "evidence": [
        {
            "framework": NaN,
            "record_id": 138,
            "chunk_id": 3,
            "distance": 0.9003,
            "text": "of the processing could not reasonably be fulfilled by other means. In order to ensure that the personal data are not kept longer than necessary, time limits should be established by the controller for erasure or for a periodic review. Every reasonable step should be taken to ensure that personal data which are inaccurate are rectified or deleted. Personal data should be processed in a manner that ensures appropriate security and confidentiality of the personal data, including for preventing unauthorised access to or use of personal data and the equipment used for the processing."
        },
        {
            "framework": NaN,
            "record_id": 165,
            "chunk_id": 1,
            "distance": 1.0012,
            "text": "(66) To strengthen the right to be forgotten in the online environment, the right to erasure should also be extended in such a way that a controller who has made the personal data public should be obliged to inform the controllers which are processing such personal data to erase any links to, or copies or replications of those personal data. In doing so, that controller should take reasonable steps, taking into account available technology and the means available to the controller, including technical measures, to inform the controllers which are processing the personal data of the data subject's request."
        },
        {
            "framework": NaN,
            "record_id": 17,
            "chunk_id": 1,
            "distance": 1.0574,
            "text": "(1) The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay and the controller shall have the obligation to erase personal data without undue delay where one of the following grounds applies: - the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; - the data subject withdraws consent on which the processing is based according to point (a) of Article 6(1), or point (a) of Article 9(2), and where there is no other legal ground for the processing; - the data subject objects to the processing pursuant to Article 21(1) and there are no overriding legitimate grounds for the processing, or the data subject objects to the processing pursuant to Article 21(2); - the personal data have been unlawfully processed; - the personal data have"
        },
        {
            "framework": NaN,
            "record_id": 126,
            "chunk_id": 1,
            "distance": 1.0697,
            "text": "(27) This Regulation does not apply to the personal data of deceased persons. Member States may provide for rules regarding the processing of personal data of deceased persons."
        },
        {
            "framework": NaN,
            "record_id": 5,
            "chunk_id": 2,
            "distance": 1.0882,
            "text": "personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay (‘accuracy’); - kept in a form which permits identification of data subjects for no longer than is necessary for the purposes for which the personal data are processed; personal data may be stored for longer periods insofar as the personal data will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with Article 89(1) subject to implementation of the appropriate technical and organisational measures required by this Regulation in order to safeguard the rights and freedoms of the data subject (‘storage limitation’); - processed in a manner that ensures appropriate security of the personal data, including protection against unauthorised or unlawful processing and against accidental loss, destruction or damage, using appropriate technical or organisational measures (‘integrity and confidentiality’)."
        }
    ],
    "compliance_score": 60,
    "recommendations": [
        "Define a clear retention period for customer personal data.",
        "Automatically delete or anonymize personal data when it is no longer required."
    ]
}